spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/sprint_demo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  port: 8088
#  servlet:
#    context-path: /mmb

mybatis:
  # 配置 mybatis xml 文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 自动将数据库表字段按照驼峰格式转换为 bean
    map-underscore-to-camel-case: true